#+title: Semantics in Generative Grammar
#+subtitle: HHU WS 2023/2024
#+author: Patrick D. Elliott
#+bibliography: ../bibliography/master.bib
#+LaTeX_CLASS: scrartcl
#+LaTeX_CLASS_OPTIONS: [letterpaper,parskip=half]
#+LaTeX_HEADER: \input{boilerplate}
#+LaTeX_COMPILER: pdflatex
#+EXPORT_FILE_NAME: ./syllabus.pdf
#+OPTIONS: ':t toc:nil
#+cite_export: biblatex

* Description

This course is intended as a first `real' introduction to formal semantics in the context of generative linguistics. That is to say, by the end of this course you'll be equipped with the necessary tools to (i) read formal semantics papers, and (ii) write a serious research paper. To get there, we'll be working through the standard graduate semantics text - "Semantics in Generative Grammar" [cite:@HeimKratzer1998], written by two of the most influential researchers in the field: Irene Heim and Angelika Kratzer. Anecdotally, I've often heard scholars refer to this text as the semantics "bible", and indeed many of the assumptions implicit in contemporary research can be traced back to this textbook. 

Unlike the course "introduction to semantics", which is empirically broad but technically shallow, in this course we'll focus on building an internally coherent analytical framework from the ground up, by focusing on a tightly constrained fragment of English. As a student, you'll be expected to do the weekly reading (i.e., a chapter from /Semantics in Generative Grammar/) and participate in class discussion. There will also be (ungraded) homework exercises taken from the textbook. 

- Class homepage: [[https://github.com/patrl/hhu-advanced-sem]] 

* Team

- *Instructor:* Dr. Patrick D. Elliott ~patrick.elliott@hhu.de~; ~https://patrickdelliott.com~
- *Secretary:* Tim Marton ~tim.marton@phil.hhu.de~

* Time and place

- Class takes place on *Wednesday* at 12:30-14:00.
- Class takes place in *2303.U1.25* 
  
* Language of instruction

The lectures, as well as the readings for this class will be in *English*.

* Leistungsnachweis

** BN requirements

- Do the weekly reading.
- Participate in class discussion.

** AP requirements

- Write a squib (i.e., a short research report).
  
* Comms

** Rocketchat

Join the rocketchat channel using the following link: [[https://rocketchat.hhu.de/invite/c8YKhS]]. Note that this is *obligatory*; in an attempt to keep things simple, I'll use this as the main channel of communication for the class, including announcements etc.

** Office hours

I hold office hours at 3-4pm on Wednesdays. You can find me in building 23.21, room 04.73. Please let me know in advance the time that you plan on dropping by, so that I can stagger appointments.

** Email

For any questions regarding the class, please post in rocketchat, so that others can benefit from the response. For any private queries, you can email me at ~patrick.elliott@hhu.edu~.

* Tentative schedule

- 14 90 minute long lectures.

| date   | class                                                     |
|--------+-----------------------------------------------------------|
| Oct 11 | Truth-conditional semantics and the Fregean Program       |
| Oct 18 | Executing the Fregean program                             |
| Oct 25 | Semantics and syntax                                      |
| Nov 1  | NO CLASS                                                  |
| Nov 8  | Nonverbal predicates, modifiers, definite descriptions    |
| Nov 15 | Relative clauses, variables, variable binding             |
| Nov 22 | Quantifiers: their semantic type                          |
| Nov 29 | Quantification and grammar                                |
| Dec 6  | Syntactic and semantic constraints on quantifier movement |
| Dec 13 | Bound and referential pronouns and ellipsis               |
| Dec 20 | Synactic and semantic binding                             |
|        | WINTER BREAK                                              |
| Jan 10 | E-type anaphora                                           |
| Jan 17 | First steps towards an intensional semantics              |
| Jan 24 | TBC                                                       |
| Jan 31 | TBC                                                       |
  
#+print_bibliography:

# Local Variables:
# jinx-languages: "en_US de_DE"
# End:

